image: node:10.16.3

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - node
        script:
          - ls -al
          - npm install -g @angular/cli@8.3.23
          - npm install
          - ng build --prod
    - step:
        name: Deploy artifacts using SCP to PROD
        deployment: production
        script:
          - pipe: atlassian/scp-deploy:0.3.3
            variables:
              USER: $user
              SERVER: $ip
              REMOTE_PATH: '/var/club/front/dist'
              LOCAL_PATH: './dist/*'
