image: node:10.16.3

pipelines:
  default:
    - step:
        name: Build and test
        caches:
          - node
        script:
          - pipe: atlassian/scp-deploy:0.3.3
            variables:
              USER: $user
              SERVER: $ip
              REMOTE_PATH: '/var/club/prod/front/dist'
              LOCAL_PATH: './dist/*'

  branches:
   staging:
    - step:
        name: Deploy artifacts using SCP to PROD
        deployment: production
        script:
          - pipe: atlassian/scp-deploy:0.3.3
            variables:
              USER: $user
              SERVER: $ip
              REMOTE_PATH: '/var/club/staging/front/dist'
              LOCAL_PATH: './dist/*'

